traefik:
  container_name: traefik
  image: containous/traefik
  ports: 
    - 8080:8080
    - 80:80
  volumes: 
    - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock

gogs-data:
  container_name: gogs-data
  image: gogs/gogs
  command: echo 'data-container for gogs'

gogs: 
  container_name: gogs
  image: gogs/gogs
  labels:
    - traefik.backend=gogs
    - traefik.port=3000
    - traefik.frontend.rule=PathPrefixStrip
    - traefik.frontend.value=/gogs
    - traefik.frontend.passHostHeader=true
  volumes_from: 
    - gogs-data
  volumes:
    - ./gogs/data/gogs/conf:/data/gogs/conf


nexus-data:
  container_name: nexus-data
  image: alpine
  command: echo 'data-container for nexus'

nexus: 
  container_name: nexus
  image: sonatype/nexus
  volumes_from: 
    - nexus-data
  environment: 
    - CONTEXT_PATH=/nexus
  labels:
    - traefik.backend=nexus
    - traefik.port=8081
    - traefik.frontend.rule=PathPrefix
    - traefik.frontend.value=/nexus
    - traefik.frontend.passHostHeader=true

jenkins: 
  container_name: jenkins
  build: ./jenkins
  command: --prefix=/jenkins
  labels:
    - traefik.backend=jenkins
    - traefik.port=8080
    - traefik.frontend.rule=PathPrefix
    - traefik.frontend.value=/jenkins
    - traefik.frontend.passHostHeader=true
  links:
    - traefik:ci-tools

rundeck:
  container_name: rundeck
  image: jordan/rundeck
  environment:
    - SERVER_URL=http://ci-tools.has-unlimited.space/rundeck/
    - RDECK_JVM=-Dserver.web.context=/rundeck
  labels:
    - traefik.backend=rundeck
    - traefik.port=4440
    - traefik.frontend.rule=PathPrefix
    - traefik.frontend.value=/rundeck
    - traefik.frontend.passHostHeader=true
  ports: 
    - 4440:4440

