- hosts : tc
  tasks: 
  - name : Install OpenJDK8
    apt: name=openjdk-8-jre-headless update_cache=true
  - name : Install tomcat
    apt: name=tomcat8

- hosts: testserv
  tasks:
  - name: Db en local pour le serveur de test
    lineinfile: dest=/etc/hosts line='127.0.0.1	db'
  
- hosts : pg
  sudo: yes
  tasks:
  - name: Update du cache apt
    apt: update_cache=yes
  - name: Install PostGreSQL et outillage
    apt: name={{item}}
    with_items:
        - postgresql-9.4
        - libpq-dev
        - python-psycopg2

- hosts : pg
  sudo: yes
  sudo_user: postgres
  vars:
    dbname: chat
    dbuser: user_rw
    dbpassword: mysecretpassword
  tasks:
  - name: Creation BDD
    postgresql_db: name={{dbname}}

  - name: Creation user
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
- hosts : rp
  tasks: 
  - name : Install HAProxy
    apt: name=haproxy update_cache=true
  - name : HAProxy config
    copy: src=files/haproxy.cfg dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
  - name: Redemarre HAProxy
    service: name=haproxy state=restarted


