- hosts : pg
  sudo: yes
  tasks:
  - name: Update du cache apt
    apt: update_cache=yes
  - name: Install PostGreSQL et outillage
    apt: name={{item}}
    with_items:
        - postgresql-9.4
        - libpq-dev
        - python-psycopg2
  - name: Postgres doit ecouter sur 0.0.0.0
    lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf line="listen_addresses = '*'"
  - name: Postgres doit autoriser les connexions sur 0.0.0.0
    lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf line="host  all  all 0.0.0.0/0 md5"
  - name: Redemarre postgresql
    service: name=postgresql state=restarted

- hosts : pg
  sudo: yes
  sudo_user: postgres
  vars:
    dbname: chat
    dbuser: user_rw
    dbpassword: mysecretpassword
  tasks:
  - name: Creation BDD
    postgresql_db: name={{dbname}}

  - name: Creation user
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} role_attr_flags=CREATEDB,SUPERUSER,LOGIN


