- hosts : tc
  tasks: 
  - name : Install OpenJDK8
    apt: name=openjdk-8-jre-headless update_cache=true
  - name : Install tomcat
    apt: name=tomcat8

- hosts: testserv
  tasks:
  - name: Db en local pour le serveur de test
    lineinfile: dest=/etc/hosts line='127.0.0.1 db'

